package com.hp.innovrex.showcase

// Debug flag - true only in debug builds
internal val IS_DEBUG: Boolean = BuildConfig.DEBUG

// BuildConfig will be generated by gradle
internal expect object BuildConfig {
    val DEBUG: Boolean
}

