package com.hp.innovrex.showcase

// Debug flag - temporarily hardcoded to true for development
// TODO: Wire up to actual build configuration
internal val IS_DEBUG: Boolean = true

// BuildConfig will be generated by gradle
internal expect object BuildConfig {
    val DEBUG: Boolean
}

